[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"

chain_id = 11155111
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/" ,"@chainlink/=lib/chainlink/", "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/", "@chiruLabs/=lib/ERC721A-Upgradeable"]

[rpc_endpoints]
sepolia = "YOUR_SEPOLIA_API_KEY"

[etherscan]
sepolia = { key = "${SEPOLIA_KEY}" }